login:
  path: /login
  controller: App\Controller\LoginController::login
register:
  path: /register
  controller: App\Controller\RegistrationController::register
page:
  path: /{page_id}
  controller: App\Controller\PageController::page
  defaults:
    page_id: 1